server.port=8087
spring.application.name=notification-service

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=satheeshprabhu012@gmail.com
spring.mail.password=ejta wuqz oacy ofbl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
eureka.instance.prefer-ip-address=true

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.tvm.notification=DEBUG

management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

management.metrics.tags.application=${spring.application.name}
