server.port=8084
spring.datasource.url=jdbc:mysql://localhost:3306/attendanceService
spring.datasource.username=root
spring.datasource.password=Satheesh@2002
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=attendance-service
logging.level.org.springframework.web=DEBUG