version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  service-registry:
    build: ./Service-Registry
    image: service-registry
    container_name: service-registry
    ports:
      - "8761:8761"

  api-gateway:
    build: ./API-Gateway
    image: api-gateway
    container_name: api-gateway
    depends_on:
      service-registry:
        condition: service_started
      auth-service:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka

  attendance-service:
    build: ./Attendance-Service
    image: attendance-service
    container_name: attendance-service
    depends_on:
      mysql:
        condition: service_healthy
      service-registry:
        condition: service_started
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/attendanceService
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka

  auth-service:
    build: ./Auth-Service
    image: auth-service
    container_name: auth-service
    depends_on:
      mysql:
        condition: service_healthy
      service-registry:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/authService
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka

  department-service:
    build: ./Department-Service
    image: department-service
    container_name: department-service
    depends_on:
      mysql:
        condition: service_healthy
      service-registry:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/departmentService
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka

  employee-service:
    build: ./Employee-Service
    image: employee-service
    container_name: employee-service
    depends_on:
      mysql:
        condition: service_healthy
      service-registry:
        condition: service_started
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employeeService
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka

  leave-service:
    build: ./Leave-Service
    image: leave-service
    container_name: leave-service
    depends_on:
      mysql:
        condition: service_healthy
      service-registry:
        condition: service_started
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/leaveService
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka

  notification-service:
    build: ./Notification-Service
    image: notification-service
    container_name: notification-service
    depends_on:
      mysql:
        condition: service_healthy
      service-registry:
        condition: service_started
    ports:
      - "8087:8087"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka

  payroll-service:
    build: ./Payroll-Service
    image: payroll-service
    container_name: payroll-service
    depends_on:
      mysql:
        condition: service_healthy
      service-registry:
        condition: service_started
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payrollService
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka

  scheduler-service:
    build: ./Scheduler-Service
    image: scheduler-service
    container_name: scheduler-service
    depends_on:
      mysql:
        condition: service_healthy
      service-registry:
        condition: service_started
    ports:
      - "8088:8088"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka


volumes:
  mysql_data: