server:
  port: 8088

spring:
  application:
    name: scheduler-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: satheeshprabhu012@gmail.com
    password: ejta wuqz oacy ofbl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    prefer-ip-address: true

# ✅ Configurable CRON Expressions
cron:
  payroll: "*/30 * * * * ?"
  attendance:
    daily: "*/30 * * * * ?"
    weekly: "*/30 * * * * ?"
  reminders:
    leaves: "*/30 * * * * ?"

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG


