server:
  port: 8082

spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://mysql:3306/employeeService
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

file:
  upload-dir: uploads/contracts

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: DEBUG
    com.tvm: DEBUG

